run:
  tests: false

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - errorlint
    - forcetypeassert
    - ifshort
    - nlreturn
    - unconvert
    - unparam
    - gocyclo
    - gocognit

linters-settings:
  revive:
    ignoreGeneratedHeader: false
    severity: warning
    confidence: 0.8
    errorCode: 0
    warningCode: 0
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: exported
  nlreturn:
    block-size: 2
