workspace: Matrix   # Workspace name. Change to use your personal workspace name

tcp_server:
  address: 0.0.0.0:8888   # TCP address service will listen on, default ":8888"
  connection_type: tcp    # net.Listen connection type

timeout:
  shutdown: 15s         # timeout for graceful shutdown, default "15s"
  read: 10s             # maximum duration for reading the entire request, including the body, default "10s"
  write: 10s            # maximum duration before timing out writes of the response, default "10s"

logging:
  level: debug          # logging level, default "info".

http:
  conn_timeout: 6s      # default timeout for all HTTP clients, default "1s"
